### ISSUE TITLE
i got this

### ISSUE THREAD

**Issue by Thomas123456789bobby** [rvandaal/BitvavoBot#1]
errno EPROTO
npm ERR! request to https://artifactory-ehv.ta.philips.com:443/artifactory/api/npm/HSDP-CP-DevNpmVirtual-Archive/zone.js/-/zone.js-0.11.4.tgz failed, reason: write EPROTO 18480:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 40

**Comment by aikrez** [comment]
Delete the package lock file and install again

**Comment by rvandaal** [comment]
@aikrez , did you run into issues with the request package? This package uses 'process' which is only available in nodejs, not when running in the browser.. can't get the code running again..

**Comment by rvandaal** [comment]
@aikrez , by now i created a BitvavoBotNode backend which solves all issues. The angular frontend is still BitvavoBot, although i first have to prepare it for the backend. But locally it works. 

Be aware though that this is a 'private' repo, no support is available (except for my messages here ;))
